package MyRobot.commands;

import MyRobot.Robot;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

public class StickDrive extends Command {
	Joystick driveStick = null;

	public StickDrive() {
		// Use requires() here to declare subsystem dependencies
		// eg. requires(chassis);

		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
		requires(Robot.drive);

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	}

	// Called just before this Command runs the first time
	protected void initialize() {
		driveStick = Robot.oi.joystick1;
	}

	// Called repeatedly when this Command is scheduled to run
	protected void execute() {
		double rawFwd = driveStick.getY();
		double rawTurn = driveStick.getX();
		double rawThrottle = driveStick.getThrottle();

		Robot.drive.driveValues(rawFwd, rawTurn);
		SmartDashboard.putNumber("Forward", rawFwd);
		SmartDashboard.putNumber("Turn", rawTurn);
	}

	// Make this return true when this Command no longer needs to run execute()
	protected boolean isFinished() {
		return false;
	}

	// Called once after isFinished returns true
	protected void end() {
	}

	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	protected void interrupted() {
	}
}
